parameters:
#    webjuegos_juegos_front.example.class: Webjuegos\JuegosFrontBundle\Example

services:
#    webjuegos_juegos_front.example:
#        class: %webjuegos_juegos_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
