<?php

namespace Webjuegos\JuegosFrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JuegoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuegoRepository extends EntityRepository
{
}
